### ISSUE TITLE
发点screenshot吧

### ISSUE THREAD

**Issue by wjx0912** [dustpg/LongUI#1]
RT

**Comment by dustpg** [comment]
感谢关注，LongUI正在进行一次最大的重写，几乎全部重写，更加轻量化，运行效率更高（暂时放在CodeUI.7z里面）。就样式而言，默认是(仿)Win10风格(可以配置类似css的样式文件), 所以screenshot就会像win10自带的程序一样

**Comment by wjx0912** [comment]
谢谢。继续关注~
