### ISSUE TITLE
vs2017编译问题

### ISSUE THREAD

**Issue by IULOVE** [dustpg/LongUI#2]
![qq 20180728152803](https://user-images.githubusercontent.com/14193276/43354238-114eecc0-927b-11e8-8b25-dc1a0e1f70a1.png)
编译错误 找不到这个符号啊·· 在哪个lib里啊·

**Comment by dustpg** [comment]
IID_IDXGIFactory2这个符号在dxguid.lib里面, 需要WinSDK8.1以上, 项目里面默认用了VS的简单扩展
```cpp
#pragma comment(lib, "dxguid")
```
AaaaUI是自己用来测试的, 里面很乱, 最近每天都在更新代码. 简单的测试可以用demo里面的工程

**Comment by IULOVE** [comment]
好吧··都编译不了···都是找不到那个符号···最新 和 8.1得sdk都不行``

**Comment by dustpg** [comment]
现在手动定义了IID_IDXGIFactory2, 能告诉我操作系统和使用的SDK版本么? 我在Win7虚拟机都没问题

**Comment by IULOVE** [comment]
win7 64位 vs2017 用 最新的sdk  10.0.17134.0 和8.1的sdk 都不行·· 我也试过把那个头文件 IID_IDXGIFactory2 的定义放过来也不行··

**Comment by dustpg** [comment]
新更新的试了没有?  头文件定义放过来? 和这个[将IID_IDXGIFactory2手动写入 #2](https://github.com/dustpg/LongUI/commit/140766d7354dbfe0f82d60dd7a7a63f037ba1c6d)一样吗?这就不可能了啊

**Comment by IULOVE** [comment]
可以编译了···不过我用v2017 需要改几个地方才可以··在 ui_manager.cpp 里引用2个头文件·· #include <filesystem/ui_file.h>  #include <core/ui_string.h>  和 ui_function.h 
![qq 20180729111820](https://user-images.githubusercontent.com/14193276/43362607-2b105ef4-9321-11e8-9daf-91a67b2efc71.png)

**Comment by dustpg** [comment]
这里是模板写得不标准,   不过我也是用的vs2017怎么没有这个问题...

头文件问题. 一直是Debug状态, 忘记测试Release了, Release忘记加这两个了
