### ISSUE TITLE
关于LongUI-0.2.1\src\container\ui_string_view.cpp下第15行代码的错误提交

### ISSUE THREAD

**Issue by yauntyour** [dustpg/LongUI#8]
![image](https://user-images.githubusercontent.com/63139381/126276427-7fac0577-71d2-42fd-91b5-f4ad2c145e6f.png)
and
![image](https://user-images.githubusercontent.com/63139381/126276625-c4753317-f00a-4620-87db-abdf91777b04.png)

**Comment by dustpg** [comment]
@yauntyour 尴尬, 自己这里 g++ 和 msc 都没问题, 不过"e871f38" 尝试修复了一下. 

不过wchar_t仅仅作为兜底类型, 目前还没有正式使用. 以后跨平台到linux也要看具体用不用

**Comment by yauntyour** [comment]
OK I will miss it,but I’m busy now.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Dust ***@***.***>
发送时间: 2021年7月23日 1:20
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [dustpg/LongUI] 关于LongUI-0.2.1\src\container\ui_string_view.cpp下第15行代码的错误提交 (#8)


Closed #8<https://github.com/dustpg/LongUI/issues/8>.

―
